Routing
team-prstmw/HousesForSaleSearcher pull request #1
Opened 2022-01-16 18:37 UTC by shadowas-py

2022-01-17 20:07 UTC, ike-tom commented on src/App.jsx
> +          <Route path="/register" element={<h1>REGISTER PAGE</h1>} />
register page will open in the modal so I'm not sure we need additional route to this page. The same for login page. After clicking sign in the modal will apear. Inside this modal you will have a switch to change modal between login modal and register modal.

2022-01-17 20:07 UTC, ike-tom commented on src/App.jsx
> +          <Route path="/login" element={<h1>LOGIN PAGE</h1>} />
same as comment for register page above

2022-01-17 20:08 UTC, ike-tom commented on src/App.jsx
> +          <Route path="/addhouse" element={<h1>ADD_HOUSE PAGE</h1>} />
you can add route for favourites

2022-01-17 20:09 UTC, ike-tom requested changes
please make corrections. Thank you :)

2022-01-18 17:56 UTC, ike-tom approved these changes

2022-01-18 19:52 UTC, FilipHalon approved these changes

2022-01-19 11:53 UTC, merged